// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbproxy

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Team struct {
	ID          pgtype.UUID `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
}
