// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbproxy

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Team struct {
	ID          pgtype.UUID
	Name        pgtype.Text
	Description pgtype.Text
}
